# Generated by Django 4.2.3 on 2023-07-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usernamer',
            new_name='username',
        ),
    ]
